baseURL = "/public/"
languageCode = "ko-KR"
defaultContentLanguage = "ko"
googleAnalytics = "UA-164685676-1"
title = "AWS ECS Workshop"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
#ignoreFiles = [ "\\.*lab3\\.*" ]

[params]
  description = "AWS ECS Workshop"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableInlineCopyToClipBoard = false
  author = "Kwangyoung Kim"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages.ko]
title = ""
weight = 1
languageName = "한국어"


[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> EKS Workshop"
url = "https://eksworkshop.com"
weight = 5

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> AppMesh Workshop"
url = "https://appmeshworkshop.com"
weight = 6

[[Languages.ko.menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/blackdog0403/ecs-cicd-hol.git"
weight = 30

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> More Resources"
url = "/more_resources"
weight = 50